name: ArcLive

options:
  bundleIdPrefix: com.arclive
  deploymentTarget:
    iOS: "17.0"

targets:
  ArcLive:
    type: application
    platform: iOS
    sources:
      - path: ArcLive
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arclive.ArcLive
        SWIFT_VERSION: 5.9
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
