name: ArcLive

options:
  bundleIdPrefix: com.arclive
  deploymentTarget:
    iOS: "17.0"

targets:
  ArcLive:
    type: application
    platform: iOS
    sources:
      - path: ArcLive
    info:
      path: ArcLive/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arclive.ArcLive
        SWIFT_VERSION: 5.9
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
